--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/alvin0319/PlayerTrade
build-by-default: true
branches:
- master
projects:
  PlayerTrade:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        branch: master
        version: ^4.1.0
...
