name: PlayerTrade
author: alvin0319
main: alvin0319\PlayerTrade\PlayerTrade
version: 1.0.2
api: 3.0.0
description: A PocketMine-MP plugin that implements trade like PC server!

extensions:
  Core: ">=7.4"

permissions:
  playertrade.command:
    description: Allows player to use /trade command
    default: true
